name: Deploy Go Application

on:
  push:
    branches:
      - main

jobs:
  MyFirstGoJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Initialize Go module
        run: go mod init go-pal-ndromo- || true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
